In [12]:
import numpy as np
import scipy
import matplotlib
import pandas

In [38]:
np_ar = np.array([[1,2,3],[4,5,6]])
print(type(np_ar), '\n', np_ar, '\n')
print(np_ar[:, :2], '\n')
print(np_ar.shape)
mask = np.array([1,0,1,0,0,1], dtype=np.bool)

<class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]] 

[[1 2]
 [4 5]] 

(2, 3)


In [55]:
np_ar

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np_ar[:,:2][np_ar[:,:2]>2]

array([4, 5])

In [59]:
np.log(np_ar)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947]])

In [64]:
print(np.linalg.norm(np_ar), np.trace(np_ar))

9.53939201417 6


In [78]:
np.random.seed(666)
a = np.random.randn(3,3)
b = np.random.randn(3,3)

In [86]:
df = pd.read_csv('BigData/winequality-red.csv', sep=';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [110]:
ph = df['pH']
bins = [3.0,3.1,3.2,3.3,3.4,3.5,3.6,3.7,3.8,3.9]
cats = pd.cut(ph,bins)# bins 分割
pd.value_counts(cats) # 计数

(3.3, 3.4]    429
(3.2, 3.3]    395
(3.1, 3.2]    254
(3.4, 3.5]    219
(3.5, 3.6]    120
(3.0, 3.1]     99
(3.6, 3.7]     32
(3.7, 3.8]     11
(3.8, 3.9]      3
Name: pH, dtype: int64

In [120]:
pd.value_counts(pd.qcut(ph,2))# 分位数 分割

(2.739, 3.31]    822
(3.31, 4.01]     777
Name: pH, dtype: int64

In [127]:
df.dropna(how='all').head() #丢掉含有缺失值的行
df.fillna(0).head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5